# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table t_config_collector (
  id                        varchar(255) not null,
  type                      varchar(255),
  name                      varchar(255),
  host                      varchar(255),
  port                      varchar(255),
  protocol                  varchar(255),
  username                  varchar(255),
  password                  varchar(255),
  namespace                 varchar(255),
  constraint pk_t_config_collector primary key (id))
;

create table t_config_job (
  id                        varchar(255) not null,
  name                      varchar(255),
  constraint pk_t_config_job primary key (id))
;

create table t_prf_controller (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_prf_disk_drive (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_prf_storage_array (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_prf_storage_port (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_prf_storage_system (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_prf_storage_volume (
  id                        bigint,
  element_name              varchar(255),
  system_name               varchar(255),
  interval                  integer,
  statistics_time           datetime,
  total_io                  double,
  read_io                   double,
  write_io                  double,
  read_seq_io               double,
  write_seq_io              double,
  read_nrm_io               double,
  write_nrm_io              double,
  total_kb                  double,
  read_kb                   double,
  write_kb                  double,
  read_seq_kb               double,
  write_seq_kb              double,
  read_nrm_kb               double,
  write_nrm_kb              double,
  total_hits                double,
  read_hits                 double,
  write_hits                double,
  read_seq_hits             double,
  write_seq_hits            double,
  read_nrm_hits             double,
  write_nrm_hits            double,
  total_time                double,
  read_time                 double,
  write_time                double,
  read_seq_time             double,
  write_seq_time            double,
  read_nrm_time             double,
  write_nrm_time            double)
;

create table t_res_controller (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  instance_number           integer,
  bus_number                integer,
  driver_name               varchar(255),
  driver_description        varchar(255),
  target                    integer,
  type                      varchar(255),
  loops                     varchar(255),
  slot                      integer,
  adapter_pair              varchar(255),
  array                     varchar(255),
  wwn                       varchar(255),
  usage_restriction         varchar(255),
  power_capacity            varchar(255),
  memory_size               integer,
  num_ports                 integer,
  constraint pk_t_res_controller primary key (id))
;

create table t_res_storage_disk (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  instance_id               varchar(255),
  device_id                 varchar(255),
  primordial                tinyint(1) default 0,
  segential_access          tinyint(1) default 0,
  total_managed_space       bigint,
  capacity                  bigint,
  remaining_managed_space   bigint,
  used_capacity             bigint,
  free_capacity             bigint,
  block_size                bigint,
  number_blocks             bigint,
  consumable_blocks         bigint,
  data_redundancy           integer,
  delta_reservation         integer,
  package_redundancy        integer,
  extent_status             varchar(255),
  raid_level                varchar(255),
  speed                     integer,
  slot                      varchar(255),
  disk_type                 varchar(255),
  is_spare                  tinyint(1) default 0,
  emc_volume_attributes_description varchar(255),
  emc_volume_attributes_description2 varchar(255),
  constraint pk_t_res_storage_disk primary key (id))
;

create table t_res_host (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  constraint pk_t_res_host primary key (id))
;

create table t_res_node (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  permanent_address         varchar(255),
  constraint pk_t_res_node primary key (id))
;

create table t_res_port (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  permanent_address         varchar(255),
  device_id                 varchar(255),
  usage_restriction         varchar(255),
  speed                     bigint,
  max_speed                 bigint,
  port_type                 varchar(255),
  link_technology           varchar(255),
  subsystem_name            varchar(255),
  device_type               varchar(255),
  subdevice_type            varchar(255),
  supported_maximum_transmission_unit bigint,
  constraint pk_t_res_port primary key (id))
;

create table t_res_port2port (
  id                        bigint auto_increment not null,
  constraint pk_t_res_port2port primary key (id))
;

create table t_res_storage_pool (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  instance_id               varchar(255),
  pool_id                   varchar(255),
  primordial                tinyint(1) default 0,
  total_managed_space       bigint,
  capacity                  bigint,
  remaining_managed_space   bigint,
  free_capacity             bigint,
  block_size                bigint,
  number_blocks             bigint,
  raid_level                varchar(255),
  consumable_blocks         bigint,
  constraint pk_t_res_storage_pool primary key (id))
;

create table t_res_storagesystem (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  nvsram_version            varchar(255),
  cache_block               integer,
  constraint pk_t_res_storagesystem primary key (id))
;

create table t_res_storage_volume (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  instance_id               varchar(255),
  device_id                 varchar(255),
  pool_id                   varchar(255),
  pool_name                 varchar(255),
  pool_instance             varchar(255),
  primordial                tinyint(1) default 0,
  segential_access          tinyint(1) default 0,
  access                    integer,
  is_mapped                 tinyint(1) default 0,
  is_underlying_redundancy  tinyint(1) default 0,
  is_composite              tinyint(1) default 0,
  is_thin_provisioned       tinyint(1) default 0,
  controller_name           varchar(255),
  total_managed_space       bigint,
  capacity                  bigint,
  remaining_managed_space   bigint,
  used_capacity             bigint,
  free_capacity             bigint,
  block_size                bigint,
  number_blocks             bigint,
  data_redundancy           integer,
  delta_reservation         integer,
  package_redundancy        integer,
  extent_status             varchar(255),
  raid_level                varchar(255),
  emc_volume_attributes_description varchar(255),
  emc_volume_attributes_description2 varchar(255),
  consumable_blocks         bigint,
  constraint pk_t_res_storage_volume primary key (id))
;

create table t_res_switch (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  domain_id                 varchar(255),
  domain_name               varchar(255),
  reboot_reason             varchar(255),
  switch_id                 varchar(255),
  switch_role               varchar(255),
  constraint pk_t_res_switch primary key (id))
;

create table t_res_tape (
  id                        bigint auto_increment not null,
  name                      varchar(255),
  element_name              varchar(255),
  display_name              varchar(255),
  creation_class_name       varchar(255),
  name_format               varchar(255),
  requested_state           integer,
  health_state              integer,
  enabled_state             integer,
  enabled_default           integer,
  operational_status        varchar(255),
  status                    varchar(255),
  status_description        varchar(255),
  system_name               varchar(255),
  discovery_at              datetime,
  update_at                 datetime,
  caption                   varchar(255),
  dedicated                 varchar(255),
  description               varchar(255),
  firmware_version          varchar(255),
  os_name                   varchar(255),
  version                   varchar(255),
  code_level                varchar(255),
  model                     varchar(255),
  manufacture               varchar(255),
  vendor                    varchar(255),
  roles                     varchar(255),
  primary_owner_name        varchar(255),
  primary_owner_contact     varchar(255),
  access_point              varchar(255),
  serial_number             varchar(255),
  part_number               varchar(255),
  ip_address                varchar(255),
  uptime                    varchar(255),
  constraint pk_t_res_tape primary key (id))
;




# --- !Downs

SET FOREIGN_KEY_CHECKS=0;

drop table t_config_collector;

drop table t_config_job;

drop table t_prf_controller;

drop table t_prf_disk_drive;

drop table t_prf_storage_array;

drop table t_prf_storage_port;

drop table t_prf_storage_system;

drop table t_prf_storage_volume;

drop table t_res_controller;

drop table t_res_storage_disk;

drop table t_res_host;

drop table t_res_node;

drop table t_res_port;

drop table t_res_port2port;

drop table t_res_storage_pool;

drop table t_res_storagesystem;

drop table t_res_storage_volume;

drop table t_res_switch;

drop table t_res_tape;

SET FOREIGN_KEY_CHECKS=1;

